<?php
	/**
	 * declared variable from submenu-page.php:
	 *
	 * $term_id
	 * $term_slug
	 */
?>


<script type="text/javascript">	
	current_frs_slide_type = '<?php echo $term_id ?>'
</script>

<?php 

global $post;

$args = array(
	'post_type' => 'pjc_slideshow',
	'posts_per_page' => 999,
	'orderby' => 'CONVERT(tonjoo_frs_order_number,signed) meta_value_num',
	'order' => 'ASC',
	'meta_key' => 'tonjoo_frs_order_number',
	'tax_query' => array(
		array(
			'taxonomy' => 'slide_type',
			'field' => 'slug',
			'terms' => $term_slug
		)
	)
);

$query = new WP_Query( $args );
$zeroHide = '';
?>

<table class="wp-list-table widefat fixed dataTable no-footer" id="table-slide" style="margin-top:20px;">
	<tbody>
	<?php if ($query->have_posts()): $zeroHide = 'hide' ?>


		<?php while ($query->have_posts()): $query->the_post(); ?>
		<?php

			//get permalink to edit
			$id = get_the_ID();
			$edit = admin_url()."post.php?post={$id}&action=edit";

			include 'ajax-row-template.php';
		?>
		<?php endwhile; ?>
	<?php endif; ?>

	</tbody>
</table>
<div class='no-slide <?php echo $zeroHide ?>'>
	<h2>The slide type seems empty ! </h2><br><a frs-add-slide  class='button button-primary'>Create First Slide</a><span class="spinner frs-button-spinner" ></span>
</div>

<?php 
	$id = null ;

	if($id==null){
		$type='Add';
	}
?>

<!-- Modal add and edit -->
<div class="frs-modal-backdrop"></div>
<div class='frs-modal-container postbox-container' style="display:none;">
		<div class="media-modal wp-core-ui hide" id="frs-tonjoo-modal">
			<div class="frs-modal-content">
				<div class="frs-modal-post">
					<form id="frs-modal-form">
						<div class="frs-table-left">
							<!-- left content generated by ajax -->
						</div>

						<div class="frs-table-right">
							<input type="text" name="title" id="frs-title" placeholder="Slider Title" value="">							
							<div frs-mediauploader="" style="margin:10px 0;">
								<img media-upload-image="" src="" class="frs-modal-image">
								<input media-upload-id="" type="hidden" name="featured_image" value="">
								<div>
					      			<input type="button" class="button-primary button-frs button" mediauploadbutton="" value="Set image">
					      			<a class="button-frs button button-danger" frs-remove-image="" data-image-default="">Remove Image</a>
								</div>		
							</div>		
							<?php 
								$settings = array(
											'textarea_rows' => '30',
											'media_buttons' => false);

								wp_editor('','frs-modal-content',$settings);
							?>
						</div>
					</form>
				</div>
			</div>
			<div class="floating-modal-button">
				<a class="button-frs button button-danger" data-post-id="" frs-delete-slide="">Delete Slide</a>
				<a class="button button-frs button-primary" frs-save-slider="" data-post-id="">Save Slider</a>
				<span class="spinner frs-button-spinner frs-button-spinner-modal "></span>								
				
				<a class="button frs-modal-close" frs-modal-close-modal="">Cancel</a>
			</div>
		</div>
	
</div>

<?php

/* Restore original Post Data */
wp_enqueue_media();
wp_reset_postdata();